Update build_native_images.yml

diff --git a/.github/workflows/build_native_images.yml b/.github/workflows/build_native_images.yml
--- a/.github/workflows/build_native_images.yml
+++ b/.github/workflows/build_native_images.yml
@@ -11,7 +11,7 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up GraalVM
         uses: graalvm/setup-graalvm@v1
@@ -32,16 +32,15 @@ jobs:
       - name: Find JAR file
         id: find_jar
         run: |
-          JAR_NAME=$(ls build/libs/ | grep '.*-fat.jar$' || echo "JAR not found")
-          if [ "$JAR_NAME" == "JAR not found" ]; then
+          JAR_NAME=$(ls build/libs/ | grep '.*-fat.jar$' || echo "")
+          if [ -z "$JAR_NAME" ]; then
             echo "Error: JAR file not found in build/libs/"
             exit 1
           fi
-          echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV
-          echo "::set-output name=jar_name::$JAR_NAME"
+          echo "jar_name=$JAR_NAME" >> $GITHUB_OUTPUT
 
       - name: Upload JAR artifact
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: fat-jar
           path: build/libs/${{ steps.find_jar.outputs.jar_name }}
@@ -52,7 +51,7 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up GraalVM
         uses: graalvm/setup-graalvm@v1
@@ -84,7 +83,7 @@ jobs:
         run: ls -l
 
       - name: Upload artifact
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: rs2fol-linux
           path: rs2fol
@@ -95,7 +94,7 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up GraalVM
         uses: graalvm/setup-graalvm@v1
@@ -127,7 +126,7 @@ jobs:
         run: ls -l
 
       - name: Upload artifact
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: rs2fol-mac
           path: rs2fol
@@ -138,7 +137,7 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up GraalVM
         uses: graalvm/setup-graalvm@v1
@@ -156,24 +155,24 @@ jobs:
       - name: Verify JAR file existence
         shell: pwsh
         run: |
-          $env:JAR_NAME="${{ needs.prepare.outputs.jar_name }}"
-          if (-Not (Test-Path "build/libs/$env:JAR_NAME")) {
-            Write-Error "Error: JAR file not found: build/libs/$env:JAR_NAME"
+          $JAR_NAME = "${{ needs.prepare.outputs.jar_name }}"
+          if (-Not (Test-Path "build/libs/$JAR_NAME")) {
+            Write-Error "Error: JAR file not found: build/libs/$JAR_NAME"
             exit 1
           }
 
       - name: Build native image
         shell: pwsh
         run: |
-          $env:JAR_NAME="${{ needs.prepare.outputs.jar_name }}"
-          native-image -H:+UnlockExperimentalVMOptions --initialize-at-build-time=com.github.ajalt.mordant.internal.nativeimage.NativeImageWin32MppImpls --no-fallback -jar "build/libs/$env:JAR_NAME" -H:Name=rs2fol
+          $JAR_NAME = "${{ needs.prepare.outputs.jar_name }}"
+          native-image -H:+UnlockExperimentalVMOptions --initialize-at-build-time=com.github.ajalt.mordant.internal.nativeimage.NativeImageWin32MppImpls --no-fallback -jar "build/libs/$JAR_NAME" -H:Name=rs2fol
 
       - name: List output files for debugging
         shell: pwsh
         run: Get-ChildItem -Path .
 
       - name: Upload artifact
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: rs2fol-windows
           path: rs2fol.exe
